### ISSUE TITLE
Beiboot client: "cluster list" function

### ISSUE THREAD

**Issue by buschNT** [Getdeck/beiboot#4]
Currently the client does not have a function to list all existing beiboot clusters. Adding this functionality would be a nice enhancement.

**Comment by Schille** [comment]
This needs to be discussed. Can you elaborate why you would like to see this functionality?

**Comment by buschNT** [comment]
E.g. in order to decide if a cluster is already created or not. Currently I detect if a cluster exists by running `get_connection`, which works, too. Other providers such as k3d and kind provide a "cluster list" option. Not sure if there are some cluster permission concerns for beiboot, which would speak against such a feature.

**Comment by Schille** [comment]
Now possible using the client
