### ISSUE TITLE
Binary naming

### ISSUE THREAD

**Issue by georgkrause** [Getdeck/beiboot#46]
In order to use the binary in the tauri app we need to have them following a specific naming scheme:

AMD64: `beibootctl-x86_64-unknown-linux-gnu`

**Comment by georgkrause** [comment]
To get the string for your platform, run `rustc -Vv | grep host | cut -f2 -d' '`

**Comment by tobifroe** [comment]
MacOS (Intel): `x86_64-apple-darwin`

**Comment by georgkrause** [comment]
I do think thats obsolete now we decided we don't want to embed the beibootctl binary into the Desktop Application.
